name: PTT

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 00:00（台灣 08:00）
  workflow_dispatch:  # 允許手動觸發
  push:
    branches-ignore:
      - main  # 避免 push 到 main 觸發 workflow

jobs:
  signin:
    runs-on: ubuntu-latest

    concurrency:
      group: ptt-signin
      cancel-in-progress: true  # 當前任務運行中時，取消新的運行

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt install -y wireguard
          pip install requests PyPtt

      - name: Configure WireGuard
        run: |
          echo "[Interface]
          PrivateKey = ${{ secrets.WG_PRIVATE_KEY }}
          Address = 192.168.1.10/24
          DNS = 8.8.8.8

          [Peer]
          PublicKey = ${{ secrets.WG_PUBLIC_KEY }}
          Endpoint = ${{ secrets.WG_SERVER_IP }}:3000
          AllowedIPs = 140.112.0.0/16
          PersistentKeepalive = 25" | sudo tee /etc/wireguard/wg0.conf

      - name: Start WireGuard VPN
        run: sudo wg-quick up wg0

      - name: Verify VPN Connection
        run: |
          sleep 5  # 等待 VPN 穩定連線
          ping -c 4 192.168.1.3  # 測試是否能連到你的主機

      - name: Run PTT Sign-in
        env:
          bot_token: ${{ secrets.BOT_TOKEN }}
          chat_id: ${{ secrets.CHAT_ID }}
          ptt_id_1: ${{ secrets.PTT_ID_1 }}
          ptt_id_2: ${{ secrets.PTT_ID_2 }}
        run: python main.py  # 確保執行 PTT 簽到腳本

      - name: Stop WireGuard VPN
        if: always()
        run: sudo wg-quick down wg0
