name: Daily Trigger

on:
  workflow_dispatch:  # 手動觸發
  schedule:
    - cron: "0 2 * * *"  # 每天 UTC 時區 2:00 AM 執行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 檢出代碼
      - name: Checkout code
        uses: actions/checkout@v2

      # 設定 Python 環境
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 安裝依賴項
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      # 執行腳本
      - name: Run the daily login script
        run: |
          poetry run python main.py
